#!/bin/bash

### TODO
# Manage several spec files


### VARS
SPEC_FILE=rpm/packetfence.spec
RPM_PACKAGE_NAME=$(rpmspec -q --queryformat="%{name}\n" $SPEC_FILE | head -n1)
RPM_PACKAGE_VERSION=$(rpmspec -q --queryformat="%{version}\n" $SPEC_FILE | head -n1)
RPM_SOURCE_TAR="$RPM_PACKAGE_NAME-$RPM_PACKAGE_VERSION.tar"

### Commands
yum install epel-release -y
tar c -f $RPM_SOURCE_TAR .
ci-build-pkg
